//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sisteducAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlunoRespostaPergunta
    {
        public int Id { get; set; }
        public Nullable<int> IdAluno { get; set; }
        public Nullable<int> IdPergunta { get; set; }
        public Nullable<bool> Acerto { get; set; }
        public Nullable<System.DateTime> DataHora { get; set; }
    
        public virtual Aluno Aluno { get; set; }
        public virtual Pergunta Pergunta { get; set; }
    }
}
